on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

name: Build and upload gccefi2linux compiler nightly build

jobs:
  build_gccefi2linux:
    name: Build gccefi2linux compiler
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Prepare tools
        run: |
          apt-get update
          apt-get -yq install build-essential\
                        wget\
                        git\
                        texinfo\
                        libz-dev\
                        flex
          apt-get autoclean
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build gccefi2linux compiler on ubuntu18
        run: |
          builds_ws=`pwd`
          check_rc () {
              rc=$?
              if [ $rc != 0 ]; then exit $rc; fi
          }
          test -z $NCPU && NCPU=$(nproc)
          cd $builds_ws
          today=$(date -u -d +%Y-%m-%d);
          GIT_COMMITTER_DATE=$(date -u -R -d "$today 00:00:00") git commit --amend
          git push -f origin
          DEPLOY_WS=${builds_ws}/deploy/linux_prod
          rm -rf objdir ${DEPLOY_WS}
          mkdir -p objdir ${DEPLOY_WS}/linux
          git show --name-only --oneline HEAD^2 >${DEPLOY_WS}/gcc_changes 2>&1 || true
          ./contrib/download_prerequisites
          cd objdir
          $PWD/../configure --prefix=${DEPLOY_WS}/linux --enable-languages=c,c++,fortran,jit,lto --disable-multilib --enable-shared --enable-host-shared --with-system-zlib --with-demangler-in-ld -enable-clocale=gnu --with-pic --enable-cloog-backend=isl --with-fmath=sse --with-cpu=corei7 --with-arch=corei7
          check_rc
